name: Dev Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          fetch-tags: true
      
      - name: Setup Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
        
      - name: Build packfile
        working-directory: ./packer
        run: python packPack.py
      
      - name: Get date
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: dev-${{env.datetime}}
          prerelease: true
          files: *.mrpack